# PyGhidra export_analysis.py
# Extract functions, strings, and cross-references for the current program
from ghidra.program.model.listing import Listing
from ghidra.program.model.symbol import RefType
from ghidra.program.model.data import StringDataType
from ghidra.util.task import TaskMonitor
from ghidra.program.model.listing import FunctionManager
from java.io import File, FileWriter, BufferedWriter

OUT_ROOT = "/usr/src/repo/007smsdev/FX2000/analysis/ghidra_exports"
if not File(OUT_ROOT).exists():
    File(OUT_ROOT).mkdirs()

prog = currentProgram
pname = prog.getName()
# sanitize program name for filenames
safe_name = pname.replace('/','_').replace(' ','_')

# Functions CSV
funcs_file = File(OUT_ROOT + File.separator + safe_name + "_functions.csv")
fw = BufferedWriter(FileWriter(funcs_file))
fw.write("name,entry,size,num_params,has_body\n")
fm = prog.getFunctionManager()
func_iter = fm.getFunctions(True)
for f in func_iter:
    try:
        name = f.getName().replace(',', '_')
        entry = f.getEntryPoint()
        size = f.getBody().getNumAddresses()
        params = 0
        try:
            params = len(f.getParameters())
        except:
            params = 0
        has_body = 'Y' if size>0 else 'N'
        fw.write("%s,%s,%d,%d,%s\n" % (name, entry, size, params, has_body))
    except Exception as e:
        # continue on errors
        pass
fw.close()

# Strings CSV and cross-reference mapping
strings_file = File(OUT_ROOT + File.separator + safe_name + "_strings.csv")
sw = BufferedWriter(FileWriter(strings_file))
sw.write("address,length,value,referenced_by_functions\n")
listing = prog.getListing()
dataIter = listing.getDefinedData(True)
refmgr = prog.getReferenceManager()
for d in dataIter:
    try:
        val = d.getValue()
        if val is None:
            continue
        # consider only Python str-like values
        if isinstance(val, str):
            addr = d.getAddress()
            length = d.getLength()
            s = val.replace('\n','\\n').replace('\r','\\r').replace('"','\\"')
            # find references to this data
            refs = refmgr.getReferencesTo(addr)
            funcs = set()
            for r in refs:
                try:
                    fromAddr = r.getFromAddress()
                    func = listing.getFunctionContaining(fromAddr)
                    if func is not None:
                        funcs.add(func.getName())
                except:
                    pass
            ref_list = ";".join(funcs)
            sw.write("%s,%d,\"%s\",\"%s\"\n" % (addr, length, s, ref_list))
    except Exception as e:
        pass
sw.close()

# Produce a small summary markdown
mdf = File(OUT_ROOT + File.separator + safe_name + "_summary.md")
mdw = BufferedWriter(FileWriter(mdf))
mdw.write("# Program: %s\n\n" % pname)
mdw.write("- Functions file: %s\n" % funcs_file.getAbsolutePath())
mdw.write("- Strings file: %s\n" % strings_file.getAbsolutePath())
mdw.write("\nGenerated by export_analysis.py\n")
mdw.close()

print("Exported functions and strings for %s to %s" % (pname, OUT_ROOT))
