CREATE TABLE IF NOT EXISTS ValidAPNs(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	ICCID VARCHAR(64) NOT NULL,
	APN VARCHAR(64),
	Valid INTEGER
CREATE INDEX IN_ValidAPNs_ICCID ON ValidAPNs( ICCID );
