#!/bin/sh
# Copyright (C) 2016 PIVA Software <www.pivasoftware.com>
#       Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>
[ "$1" != "run" -a "$1" != "stop_mon" ] && return
UCI_CONFIG_DIR="/opt/nvtl/data/tr069/config"
UCI_SAVE_DIR="/opt/nvtl/data/tr069/.uci.dmc"
UCI_GET_VARSTATE="/usr/bin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} -P $UCI_SAVE_DIR get"
thermal_type=""
for i in `seq 1 100`; do
        if [ -f /sys/class/thermal/thermal_zone$i/type ]; then
                thermal_type=`cat /sys/class/thermal/thermal_zone$i/type`
                if [ $thermal_type == "xo-therm-usr" ]; then
			TEMP_FILE_NAME="/sys/class/thermal/thermal_zone$i/temp"
			MODE_FILE_NAME="/sys/class/thermal/thermal_zone$i/mode"
			break
TMPFILE="/tmp/temp_mon.txt"
READ_TMPFILE="/tmp/read_temp_mon.txt"
DEFAULT_SLEEP_TIME=2
temp_monitor_launch(){
        local temp_value saved_temp_value min_value max_value def_value
	def_value=-274000
        cur_time=$(modem2_cli get_network_time | grep Timestamp: | cut -d '[' -f 2 | cut -d ']' -f 1)
	while [ $cur_time -lt 1500000000 ]
		sleep 2
		cur_time=$(modem2_cli get_network_time | grep Timestamp: | cut -d '[' -f 2 | cut -d ']' -f 1)
	mode=$(cat $MODE_FILE_NAME)
	first=0
	if [ $mode == "enabled" ] ; then
		temp_value=$(cat $TEMP_FILE_NAME)
        	min_value=$temp_value
        	max_value=$temp_value
		reset_time=$cur_time
		first=1
		printf "RESET_TIME: $reset_time\n" >$TMPFILE
		printf "MIN_TIME: $cur_time \n" >> $TMPFILE
		printf "MIN_TEMP: $min_value\n" >>$TMPFILE
		printf "MAX_TIME: $cur_time\n" >> $TMPFILE
		printf "MAX_TEMP: $max_value\n" >>$TMPFILE
		printf "LAST_TIME: $reset_time\n" >>$TMPFILE
		cp $TMPFILE $READ_TMPFILE
		min_value=0
		max_value=0
        while [ -f $TMPFILE ]
        do
		mode=$(cat $MODE_FILE_NAME)
		if [ $mode == "enabled" ] ; then
			low_value1=$($UCI_GET_VARSTATE easycwmp.@device[0].temp_low_alarm_value)
			high_value1=$($UCI_GET_VARSTATE easycwmp.@device[0].temp_high_alarm_value)
			low_value=$(awk "BEGIN {printf \"%d\",$low_value1*1000}")
			high_value=$(awk "BEGIN {printf \"%d\",$high_value1*1000}")
                	sleep `$UCI_GET_VARSTATE easycwmp.@device[0].temp_polling_interval`
			temp_value=$(cat $TEMP_FILE_NAME)
                	cur_time=$(modem2_cli get_network_time | grep Timestamp: | cut -d '[' -f 2 | cut -d ']' -f 1)
			if [ $temp_value -lt $min_value ] || [ $first == 0 ] ; then
        			min_value=$temp_value
				sed -i "s/MIN_TIME:.*/MIN_TIME: ${cur_time}/" $TMPFILE
				sed -i "s/MIN_TEMP:.*/MIN_TEMP: ${min_value}/" $TMPFILE
			elif [ $temp_value -gt $max_value ] || [ $first == 0 ] ; then
        			max_value=$temp_value
				sed -i "s/MAX_TIME:.*/MAX_TIME: ${cur_time}/" $TMPFILE
				sed -i "s/MAX_TEMP:.*/MAX_TEMP: ${max_value}/" $TMPFILE
			if [ $min_value -le $low_value ] ; then
				p=`grep "LOW" $TMPFILE`
				if [ "$p" == "" ] ; then
					printf "LOW_TIME: $cur_time\n" >>$TMPFILE
			 		printf "LOW_TEMP: $min_value\n" >>$TMPFILE
				else
					sed -i "s/LOW_TIME:.*/LOW_TIME: ${cur_time}/" $TMPFILE
					sed -i "s/LOW_TEMP:.*/LOW_TEMP: ${min_value}/" $TMPFILE
			if [ $max_value -ge $high_value ] ; then
				p=`grep "HIGH" $TMPFILE`
				if [ "$p" == "" ] ; then
					printf "HIGH_TIME: $cur_time\n" >>$TMPFILE
			 		printf "HIGH_TEMP: $max_value\n" >>$TMPFILE
				else
					sed -i "s/HIGH_TIME:.*/HIGH_TIME: ${cur_time}/" $TMPFILE
					sed -i "s/HIGH_TEMP:.*/HIGH_TEMP: ${max_value}/" $TMPFILE
			sed -i "s/LAST_TIME:.*/LAST_TIME: ${cur_time}/" $TMPFILE
			cp $TMPFILE $READ_TMPFILE
			first=1
			sleep $DEFAULT_SLEEP_TIME
        done
temp_monitor_stop() {
	rm /tmp/temp_mon.txt
[ "$1" == "run" ] && { temp_monitor_launch 2>/dev/null; exit 0; }
[ "$1" == "stop_mon" ] && temp_monitor_stop 2>/dev/null
