CREATE TABLE IF NOT EXISTS CustomAPN(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	ICCID VARCHAR(64) NOT NULL ON CONFLICT ROLLBACK,
	APN VARCHAR(64),
	Username VARCHAR(64),
	Password VARCHAR(64),
	Auth INTEGER,
	IMSI VARCHAR(64),
	Profileid INTEGER,
	Pdptype INTEGER   NOT NULL ON CONFLICT ROLLBACK,
	Apnflag INTEGER   NOT NULL ON CONFLICT ROLLBACK 
CREATE UNIQUE INDEX IN_CustomAPN_ID ON CustomAPN( ID );
