CREATE TABLE IF NOT EXISTS KnownDevices(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	Mac VARCHAR(20) NOT NULL ON CONFLICT ROLLBACK,
	Name VARCHAR(64),
	VendorClass VARCHAR(64),
	ParamReqList VARCHAR(572),
	LastConnectedDate VARCHAR(25),
	Interface INTEGER
CREATE TABLE IF NOT EXISTS DataSessions(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	IMSI VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	ICCID VARCHAR(25),
	MDN VARCHAR(20) NOT NULL ON CONFLICT ROLLBACK,
	FWVersion VARCHAR(20),
	Interface INTEGER,
	Bearer INTEGER,
	MonoStart INTEGER,
	MonoEnd INTEGER,
	StartDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	EndDate VARCHAR(25),
	IPv4 VARCHAR(25),
	IPv6 VARCHAR(50),
	Roaming INTEGER,
	BytesTXIPv4 BIGINT,
	BytesRXIPv4 BIGINT,
	BytesTXIPv6 BIGINT,
	BytesRXIPv6 BIGINT
CREATE TABLE IF NOT EXISTS EthDataSessions(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	MAC VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	FWVersion VARCHAR(20),
	Interface INTEGER,
	MonoStart INTEGER,
	MonoEnd INTEGER,
	StartDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	EndDate VARCHAR(25),
	IPv4 VARCHAR(25),
	IPv6 VARCHAR(50),
	BytesTXIPv4 BIGINT,
	BytesRXIPv4 BIGINT,
	BytesTXIPv6 BIGINT,
	BytesRXIPv6 BIGINT
CREATE TABLE IF NOT EXISTS UsageLogs(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	Mac VARCHAR(20) NOT NULL ON CONFLICT ROLLBACK,
	IDDataSession INTEGER NOT NULL ON CONFLICT ROLLBACK,
	IDKnownDevice INTEGER NOT NULL ON CONFLICT ROLLBACK,
	StartDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	EndDate VARCHAR(25),
	IPv4 VARCHAR(25),
	IPv6 VARCHAR(50),
	UploadStatus INTEGER,
	State       INTEGER,
	BytesTX     BIGINT,
	BytesRX     BIGINT,
	BytesTXIPv4 BIGINT,
	BytesRXIPv4 BIGINT,
	BytesTXIPv6 BIGINT,
	BytesRXIPv6 BIGINT,
	FOREIGN KEY(IDDataSession) REFERENCES DataSessions ( ID ),
	FOREIGN KEY(IDKnownDevice) REFERENCES KnownDevices ( ID )
CREATE TABLE IF NOT EXISTS SiteAccess(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	Mac VARCHAR(20) NOT NULL ON CONFLICT ROLLBACK,
	IDKnownDevice INTEGER NOT NULL ON CONFLICT ROLLBACK,
	AccessDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	Domain VARCHAR(255) NOT NULL ON CONFLICT ROLLBACK,
	FOREIGN KEY(IDKnownDevice) REFERENCES KnownDevices ( ID )
CREATE INDEX IN_DataSessions_StartDate_EndDate ON DataSessions( StartDate, EndDate );
CREATE UNIQUE INDEX IN_KnownDevices_Mac ON KnownDevices( Mac );
CREATE TABLE IF NOT EXISTS GlobalDataCounters(
	IDGlobalDataCounters INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	Bearer INTEGER UNIQUE ON CONFLICT ROLLBACK,
	BytesIn  INTEGER, 
	BytesOut INTEGER, 
	ConnectionTimeSeconds INTEGER
CREATE TABLE IF NOT EXISTS DataPlanResetDate(
	IDDataPlanResetDate INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	ResetDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK
CREATE TABLE IF NOT EXISTS SimResetDate(
	IDSimResetDate INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	IMSI VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	ResetDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK
CREATE TABLE IF NOT EXISTS EthResetDate(
	IDEthResetDate INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	ResetDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK
CREATE TABLE IF NOT EXISTS EthMacResetDate(
	IDEthMacResetDate INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	MAC VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	ResetDate VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK
CREATE TABLE IF NOT EXISTS SystemDefaults(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	Version VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	SupportClientData INTEGER 
CREATE TABLE IF NOT EXISTS SimInfo(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	ICCID VARCHAR(25) NOT NULL ON CONFLICT ROLLBACK,
	IMSI VARCHAR(25),
	MDN VARCHAR(25) 
INSERT INTO SystemDefaults("Version", "SupportClientData") VALUES ('1.5', 1);
