CREATE TABLE IF NOT EXISTS Goldrec(
	ID INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
	imsi VARCHAR(64),
	iccid VARCHAR(64),
	oper_name VARCHAR(64),
	cellid VARCHAR(64),
	bandid INTEGER,
	service INTEGER,
	bearer INTEGER,
	rsrp INTEGER,
	perf_rating INTEGER,
	model VARCHAR(64),
	sku VARCHAR(64),
	imei VARCHAR(64),
	mac VARCHAR(64),
	ipv4addr VARCHAR(64),
	ipv6addr VARCHAR(64),
	firmware_ver VARCHAR(64),
	installed_id VARCHAR(64),
	instal_start_dt VARCHAR(64),
	instal_end_dt VARCHAR(64),
	instal_locn VARCHAR(64),
	x_coord INTEGER,
	y_coord INTEGER,
	z_coord INTEGER,
	throuput_est INTEGER,
	wifissid  VARCHAR(64),
	wifipwd  VARCHAR(64),
	extantenna	INTEGER,
	sim_egci	INTEGER,
	manufacturer	VARCHAR(64),
	model_name	VARCHAR(64),
	os_type		VARCHAR(64),
	passcode	VARCHAR(64),
	pri_ver		INTEGER,
	rsrq		INTEGER,
	snr		INTEGER,
	endc		INTEGER	
);
CREATE UNIQUE INDEX IN_Goldrec_ID ON Goldrec( ID );



