# Analyze Critical Unlock Binaries with Ghidra
# Focus on the 3 most important binaries: libmal_qct.so, modem2_cli, libqmi.so.1.0.0

param(
    [string]$BinaryDir = "F:\repo\zerosms\analysis\complete_device_dump\_ALL_ELF_BINARIES",
    [string]$GhidraPath = "F:\download\ghidra_11.4.3_PUBLIC_20251203\ghidra_11.4.3_PUBLIC",
    [string]$OutputDir = "F:\repo\zerosms\analysis\critical_binaries_analysis"
)

Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "  Critical Binaries Ghidra Analysis" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan

# Critical binaries to analyze
$criticalBins = @(
    "libmal_qct.so",   # Primary unlock library (353 functions, unlock @ 0x00039f4c)
    "modem2_cli",      # Modem CLI (196 commands, 27 unlock functions)
    "libqmi.so.1.0.0"  # QMI library (114 QMI functions)
)

# Find the binaries
Write-Host "[*] Locating critical binaries..." -ForegroundColor Yellow
$binaries = @()
foreach ($binName in $criticalBins) {
    $found = Get-ChildItem -Path $BinaryDir -Recurse -Filter $binName -File | Select-Object -First 1
    if ($found) {
        $binaries += $found
        Write-Host "  [+] Found: $binName ($([math]::Round($found.Length/1KB,2)) KB)" -ForegroundColor Green
    }
    else {
        Write-Host "  [-] Missing: $binName" -ForegroundColor Red
    }
}

if ($binaries.Count -eq 0) {
    Write-Host "[!] ERROR: No critical binaries found" -ForegroundColor Red
    exit 1
}

# Create output directories
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
$projectDir = Join-Path $OutputDir "ghidra_project"
$decompileDir = Join-Path $OutputDir "decompiled"
$reportDir = Join-Path $OutputDir "reports"
New-Item -ItemType Directory -Path $projectDir -Force | Out-Null
New-Item -ItemType Directory -Path $decompileDir -Force | Out-Null
New-Item -ItemType Directory -Path $reportDir -Force | Out-Null

# Create Ghidra Python script
$pythonScript = Join-Path $OutputDir "analyze_critical.py"
$scriptContent = @"
# Ghidra Headless Analysis Script - Critical Binaries
# Auto-generated by analyze_critical_binaries.ps1

from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor
from java.io import File, FileWriter

def main():
    monitor = ConsoleTaskMonitor()
    program = getCurrentProgram()
    
    # Get program info
    program_name = program.getName()
    output_dir = "$($decompileDir.Replace('\', '/'))"
    report_dir = "$($reportDir.Replace('\', '/'))"
    
    # Initialize decompiler
    ifc = DecompInterface()
    ifc.openProgram(program)
    
    # Analysis
    print("[*] Analyzing: " + program_name)
    
    # Get function listing
    function_manager = program.getFunctionManager()
    functions = function_manager.getFunctions(True)
    
    function_list = []
    interesting_functions = []
    
    # Keywords for unlock-related functions
    unlock_keywords = ["unlock", "carrier", "perso", "nv", "qmi", "modem", "verify", "check", "auth"]
    
    for func in functions:
        func_name = func.getName()
        func_addr = func.getEntryPoint().toString()
        function_list.append({'name': func_name, 'address': func_addr})
        
        # Check for interesting functions
        func_name_lower = func_name.lower()
        if any(keyword in func_name_lower for keyword in unlock_keywords):
            interesting_functions.append({'name': func_name, 'address': func_addr})
    
    print("[+] Total functions: " + str(len(function_list)))
    print("[+] Interesting functions: " + str(len(interesting_functions)))
    
    # Write function report
    report_file = File(report_dir, program_name + "_functions.txt")
    writer = FileWriter(report_file)
    writer.write("=" * 80 + "\n")
    writer.write("FUNCTION ANALYSIS: " + program_name + "\n")
    writer.write("=" * 80 + "\n\n")
    writer.write("Total functions: " + str(len(function_list)) + "\n")
    writer.write("Interesting functions: " + str(len(interesting_functions)) + "\n\n")
    
    writer.write("=" * 80 + "\n")
    writer.write("INTERESTING FUNCTIONS (Unlock-related)\n")
    writer.write("=" * 80 + "\n")
    for func in interesting_functions:
        writer.write(func['address'] + " | " + func['name'] + "\n")
    
    writer.write("\n" + "=" * 80 + "\n")
    writer.write("ALL FUNCTIONS\n")
    writer.write("=" * 80 + "\n")
    for func in function_list[:100]:  # First 100 functions
        writer.write(func['address'] + " | " + func['name'] + "\n")
    
    writer.close()
    print("[+] Report written: " + report_file.getPath())
    
    # Decompile interesting functions
    if len(interesting_functions) > 0:
        decompile_file = File(output_dir, program_name + "_decompiled.c")
        dec_writer = FileWriter(decompile_file)
        
        for func_info in interesting_functions[:20]:  # First 20 interesting functions
            try:
                func = function_manager.getFunctionAt(program.getAddressFactory().getAddress(func_info['address']))
                if func:
                    results = ifc.decompileFunction(func, 30, monitor)
                    if results and results.decompileCompleted():
                        dec_writer.write("// " + "=" * 70 + "\n")
                        dec_writer.write("// Function: " + func_info['name'] + "\n")
                        dec_writer.write("// Address: " + func_info['address'] + "\n")
                        dec_writer.write("// " + "=" * 70 + "\n")
                        dec_writer.write(results.getDecompiledFunction().getC())
                        dec_writer.write("\n\n")
            except Exception as e:
                print("[!] Failed to decompile: " + func_info['name'])
        
        dec_writer.close()
        print("[+] Decompilation written: " + decompile_file.getPath())

if __name__ == '__main__':
    main()
"@

Set-Content -Path $pythonScript -Value $scriptContent -Encoding UTF8
Write-Host "[+] Created analysis script: $pythonScript" -ForegroundColor Green

# Analyze each binary
$ghidraHeadless = Join-Path $GhidraPath "support\analyzeHeadless.bat"
$count = 0
$total = $binaries.Count

foreach ($binary in $binaries) {
    $count++
    $percent = [math]::Round(($count / $total) * 100)
    Write-Host ""
    Write-Host "[$count/$total] ($percent%) Analyzing: $($binary.Name)" -ForegroundColor Cyan
    Write-Host "  Path: $($binary.FullName)" -ForegroundColor Gray
    Write-Host "  Size: $([math]::Round($binary.Length/1KB,2)) KB" -ForegroundColor Gray
    
    $binaryName = $binary.Name -replace '\.[^.]*$', ''  # Remove extension
    
    # Run Ghidra headless
    $ghidraArgs = @(
        $projectDir,
        "CriticalAnalysis",
        "-import", $binary.FullName,
        "-scriptPath", $OutputDir,
        "-postScript", "analyze_critical.py",
        "-deleteProject",
        "-overwrite"
    )
    
    Write-Host "  [*] Running Ghidra analysis..." -ForegroundColor Yellow
    $proc = Start-Process -FilePath $ghidraHeadless -ArgumentList $ghidraArgs -Wait -NoNewWindow -PassThru
    
    if ($proc.ExitCode -eq 0) {
        Write-Host "  [+] Analysis complete" -ForegroundColor Green
    }
    else {
        Write-Host "  [!] Analysis failed (exit code: $($proc.ExitCode))" -ForegroundColor Red
    }
}

Write-Host ""
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "  Analysis Complete" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host "[+] Decompiled code: $decompileDir" -ForegroundColor Green
Write-Host "[+] Function reports: $reportDir" -ForegroundColor Green
Write-Host ""
Write-Host "[*] Next steps:" -ForegroundColor Yellow
Write-Host "  1. Review function reports for unlock-related functions"
Write-Host "  2. Examine decompiled code for algorithm details"
Write-Host "  3. Compare with previous findings from Part 2/Part 3"
